### ISSUE TITLE
Information on rochcor2015

### ISSUE THREAD

**Issue by xealits** [cms2l2v/2l2v_fwk#163]
Could someone post a link to the twiki/talk/source of `https://github.com/cms2l2v/2l2v_fwk/blob/master/interface/rochcor2015.h`?
Where do the numbers come from?

**Comment by xealits** [comment]
it seems to be comming from https://github.com/cms-tau-pog/jetToTauFakeRate/blob/master/src/rochcor2015.cc

**Comment by vischia** [comment]
No, it's the contrary.

I took it from cms2l2v and put it there because I needed it there.

Cheers,
Pietro

2016-06-28 15:18 GMT+02:00 Alex Toldaiev <notifications@github.com>:

> it seems to be comming from
> https://github.com/cms-tau-pog/jetToTauFakeRate/blob/master/src/rochcor2015.cc
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cms2l2v/2l2v_fwk/issues/163#issuecomment-229045868>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEBGqMtqhEq71M91hM8xmGjGQlTkIPzlks5qQR8dgaJpZM4It4Ai>
> .
>



-- 
Pietro Vischia
LIP-Lisboa                   Av. Elias Garcia 14 - 1º, 1000-149 Lisboa,
Portugal
mobiles: 00351 96 724 9239 (PT), 0039 340 51 69 388 (IT)
office: 00351 21 799 5017
mail: pietro.vischia@gmail.com
skype: rambling_hadron

**Comment by xealits** [comment]
so, where did the cms2l2v version come from in the first place?
The code there contains quite a lot of hardcoded numbers -- it's better to know where they come from/to which CMSSW release/muon-POG studies they correspond.

**Comment by HuguesBrun** [comment]
Hello Alex,
* you can find the documentation of the Rochester correction in a Twiki [here](https://twiki.cern.ch/twiki/bin/viewauth/CMS/RochcorMuon) (I think that in cms2l2v we used the 74X/promptRECO of the correction but you can double check from there)
* the last talk in the muon POG related to this method can be found [here](https://indico.cern.ch/event/533054/contributions/2171540/attachments/1274536/1891597/rochcor_run2_MuonPOG_051716.pdf) 

Hope that it helps ! 
Hugues

**Comment by xealits** [comment]
Thanks!
