### ISSUE TITLE
Regex matching for plotter not working

### ISSUE THREAD

**Issue by vischia** [cms2l2v/2l2v_fwk#238]
Hi, the new regexp matching for the plotter does not seem to correctly match.

I have plots starting for "wjet_", and none of the following works:

"wjet_"
"(wjet_.*)"
"wjet(_.*)"
"wjet_(.*)"
"wjet_.*"
I even tried "wjet_*", which is not proper regex, and it does not work either.

Am I doing something wrong? Which is the syntax which is expected to work?

Best,
Pietro

**Comment by amagitte** [comment]
Hi Pietro,

Sorry for my late answer.
if you want that regex works you are obliged to specify the entire name because what we are using is the following method[*] https://github.com/cms2l2v/2l2v_fwk/blob/master/interface/RootUtils.h#L79
If you look at this page [**], you can see that it needs the "entire character sequence".

You can find some example in our submit.sh [***].

Cheers,
Alessio

[*]  https://github.com/cms2l2v/2l2v_fwk/blob/master/interface/RootUtils.h#L79
[**] http://en.cppreference.com/w/cpp/regex/regex_match
[***] https://github.com/cms2l2v/2l2v_fwk/blob/master/test/hzz2l2v/submit.sh#L198

**Comment by hdelanno** [comment]
Just one more pice of information.
You can also use the option '-t' with submit.sh. In this case it is a regex but with the dataset name.

Example, if you want this datasat: https://github.com/cms2l2v/2l2v_fwk/blob/master/test/hzz2l2v/samples_ichep2016.json#L72
you can do sh submit.sh 1.0 -t WZ3

Hope it helps.

**Comment by vischia** [comment]
Hi @hdelanno , 

thanks for the information! For the dataset names I am using the "--key" parameter with much profit!

In the end the issue was that my regex is very complicated, and I had put lots of parentheses that are not needed and that actually were breaking the expression :)

Thanks! I am closing the issue :)

Best,
Pietro
